name: alpine

on:
  workflow_dispatch:
    inputs:
      tag:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          echo "FROM alpine:${{ github.event.inputs.tag }}
          RUN apk add --no-cache  ca-certificates tzdata nghttp2-libs curl tcpdump
          ENV TZ=Asia/Shanghai"  > Dockerfile
          
          docker buildx create --use
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
          docker  buildx build -t basefly/alpine:${{ github.event.inputs.tag }} . --platform=linux/arm,linux/arm64,linux/amd64   --push
