name: Docker Image CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} 
        ls 
        docker  buildx build -t basefly/alpine  --platform=linux/arm,linux/arm64,linux/amd64  debug/Dockerfile  --push
