name: gc


on:
   workflow_dispatch
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker buildx create --use
        docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }} 
        echo 'FROM gcr.io/datadoghq/operator:0.8.1' > Dockerfile
        docker  buildx build -t basefly/datadoghq-operator:0.8.1    --platform=linux/arm,linux/arm64,linux/amd64  .  --push
